"""Generic Alembic script template used by `alembic revision`.

This is the default template content Alembic expects when the
`script_location` in `alembic.ini` points to this local folder.
"""

"""create initial tables

Revision ID: b6ad308c433e
Revises: 
Create Date: 2025-08-25 16:54:15.387854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6ad308c433e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	pass
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	pass
	# ### end Alembic commands ###
